
### GET
GET http://localhost:3000/api/katutiedot/61.498139/23.7515

### GET
GET http://localhost:3000/api/katutiedot/123.4/kissa

### GET
GET http://localhost:3000/api/katutiedot/61.56291234/23.98469123

